name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Aktualizacja raz dziennie
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: matgorzynski
          template: classic
          base: metadata
          config_timezone: Europe/Warsaw
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
